# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c7f415e7-c414-475c-95a1-6373321dfed1";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."cryptblock".device = "/dev/disk/by-uuid/8b52bb5d-aef5-47e0-b363-6b4683b9b31e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/16F3-03AB";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 16;
  powerManagement.cpuFreqGovernor = "ondemand";
}
